export type LatticeCard = {
  id: string;
  name: string;
  set: string;
  tier: 'Common' | 'Rare' | 'Legendary' | 'Ultimate';
  shell: string;
  imagePath: string;
  imageAlt: string;
  flavor: string;
  flavorAttrib: string;
  echo: string;
};

export const LATTICE_CARDS: LatticeCard[] = [
  {
    id: 'bs1-c01',
    name: "Watson's Arrival",
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c01/v1.webp',
    imageAlt: 'Watson on the threshold of 221B Baker Street, 1881',
    flavor:
      'Name: Watson, J.H. Condition: serviceable. Time: 11.23. Comment: looked at the deerstalker first.',
    flavorAttrib: "Mrs H.'s visitor book, 1881",
    echo: 'The deerstalker in the hall was not dry. Someone had been out in the rain that morning and returned before Watson arrived.',
  },
  {
    id: 'bs1-c02',
    name: 'The Thinking Pose',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c02/v1.webp',
    imageAlt: 'Holmes at the mantelpiece, fingertips at temple, mid-deduction',
    flavor:
      'When he was silent like that, it was not that he had nothing to say. It was that whatever he was about to say would close the case.',
    flavorAttrib: 'Watson, casebook',
    echo: 'The pipe in his hand had been unlit for an hour. He smoked before a case and after. During, he needed his hands clear.',
  },
  {
    id: 'bs1-c03',
    name: "Watson's Notebook",
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c03/v1.webp',
    imageAlt: "Watson at his writing desk, pen to notebook page, midnight",
    flavor:
      'To whoever finds this: do not read volume IV without reading III first. The explanation is in the margin of page 91.',
    flavorAttrib: 'J.H.W.',
    echo: "Page 91 of volume III contains a single line: 'He survived. The notation is sealed per his request.'",
  },
  {
    id: 'bs1-c06',
    name: 'The Persian Slipper',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c06/v1.webp',
    imageAlt: 'The Persian slipper on the 221B mantelpiece, tobacco-heavy and worn',
    flavor:
      'The slipper was the only object in 221B that was never moved. It outlasted three tenants, two attempted arson, and one particularly eventful Tuesday.',
    flavorAttrib: '',
    echo: "The third tenant whose departure the slipper outlasted was never identified in Watson's published accounts. The inventory of 1887 lists him only as 'the August occupant.'",
  },
  {
    id: 'bs1-l01',
    name: 'The Violin at Midnight',
    set: 'Baker Street · BS-1',
    tier: 'Legendary',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-l01/v1.webp',
    imageAlt: 'Holmes alone at 2am with the violin, Baker Street fog beyond the window',
    flavor:
      '2.15 AM. Violin. Not bored — the boredom-music is different. This is the other kind. I will not ask which case.',
    flavorAttrib: 'Watson',
    echo: "Watson owned three of Holmes's violin compositions. He never had them transcribed. He said the notation would not capture what made them what they were.",
  },
  {
    id: 'bs1-r01',
    name: 'V.R. in the Plaster',
    set: 'Baker Street · BS-1',
    tier: 'Rare',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-r01/v1.webp',
    imageAlt: "Holmes having shot 'V.R.' into the sitting-room wall, revolver still at his side",
    flavor:
      'Mr Watson — the plaster again. Fourth time this year. He has spelled Victoria correctly on this occasion.',
    flavorAttrib: 'Mrs H., note, undated',
    echo: "Of the three earlier 'V.R.' engravings, two were solved cases. The third was never discussed.",
  },
  {
    id: 'bs1-r02',
    name: 'The Street Deduction',
    set: 'Baker Street · BS-1',
    tier: 'Rare',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-r02/v1.webp',
    imageAlt: 'Holmes at the 221B first-floor window, observing a figure in the street below',
    flavor:
      'He described the man in the brown coat in eleven sentences before the man had reached the corner. He was right about ten of them. The eleventh surprised him.',
    flavorAttrib: 'Watson, casebook, 1887',
    echo: 'The man in the brown coat was never identified. Holmes kept the window for a week after, which Watson understood to mean he had not yet closed the case.',
  },
  {
    id: 'bs1-u01',
    name: 'You Have Been in Afghanistan, I Perceive',
    set: 'Baker Street · BS-1',
    tier: 'Ultimate',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-u01/v1.webp',
    imageAlt: "Holmes and Watson at the moment of first meeting, St Bartholomew's Hospital, 1881",
    flavor:
      'He looked at me for perhaps four seconds. Then he told me things about myself I had not told him. The handshake was still warm.',
    flavorAttrib: 'Watson, casebook, 1881',
    echo: "The mud on Watson's boot was the wrong Kandahar mud — the kind from the eastern outskirts. Holmes noted it but did not include it in the deduction he spoke aloud.",
  },
  {
    id: 'bs1-c04',
    name: 'Mrs Hudson on the Stairs',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c04/v1.webp',
    imageAlt: 'Mrs Hudson ascending the 221B staircase with a tea tray',
    flavor:
      'To Mr Watson — replacement tea service, third this quarter. The violin vibrations crack the cups. Please advise.',
    flavorAttrib: 'Mrs H.',
    echo: "The fourth tea service is listed in Watson's household accounts as 'sundry expenditure, violin-related.' The fifth is listed differently. The sixth is not listed.",
  },
  {
    id: 'bs1-c05',
    name: 'The Chemistry Bench',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c05/v1.webp',
    imageAlt: 'Holmes at the 221B chemistry bench, magnifying lens in hand, wholly absorbed',
    flavor: 'Experiment 7, batch C. Do not disturb the precipitate. The shadow is correct.',
    flavorAttrib: 'H.H.',
    echo: 'The label for Experiment 7, batch C appears in Watson\'s case-notes as an addendum to the Irene Adler file, without explanation.',
  },
  {
    id: 'bs1-c07',
    name: 'The First Client',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c07/v1.webp',
    imageAlt: 'Holmes and Watson receiving a client in the 221B sitting room',
    flavor:
      'Client: name withheld. Duration: eleven minutes. Case accepted: no. Reason for refusal: unstated, but I recognized the expression.',
    flavorAttrib: 'Watson, unsorted',
    echo: "The expression Watson recognized from this client's case is referenced twice more in his unpublished notebooks — both times in the same margins as notes on Moriarty.",
  },
  {
    id: 'bs1-c08',
    name: 'The Disguise Wardrobe',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c08/v1.webp',
    imageAlt: "The open wardrobe of disguises in Holmes's room at 221B, one peg empty",
    flavor:
      "Holmes kept his disguises as another man might keep debts — catalogued, each one owed to a specific occasion, none forgiven until the case was closed.",
    flavorAttrib: '',
    echo: "The empty peg in Watson's wardrobe inventory is listed as 'the dockworker, used three times, borrowed once by unnamed third party at Holmes's request.' The third party is not named in the inventory.",
  },
  {
    id: 'bs1-c09',
    name: 'The Telegram',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c09/v1.webp',
    imageAlt: 'Watson holds an arrived telegram; Holmes reaches for his coat',
    flavor: 'Come at once if convenient. If inconvenient, come all the same.',
    flavorAttrib: "Lestrade. Watson's note: third this week.",
    echo: 'The telegram was the second of three that week. The third was sent but never delivered — Watson found it unopened in a messenger\'s satchel six months later, the address crossed out in an unfamiliar hand.',
  },
  {
    id: 'bs1-c10',
    name: 'The Baker Street Irregulars',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c10/v1.webp',
    imageAlt: 'Holmes dispatching the Baker Street Irregulars from the 221B doorstep',
    flavor:
      'He paid them twice what any of them asked and three times what Scotland Yard paid its informants. He never mentioned this.',
    flavorAttrib: 'Watson, casebook, 1882',
    echo: "Watson's account of the payment rates is not in any published case. It appears only in the unnumbered volume of his casebook, in the section he titled 'Things he would not want printed.'",
  },
  {
    id: 'bs1-r03',
    name: 'The Photograph',
    set: 'Baker Street · BS-1',
    tier: 'Rare',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-r03/v1.webp',
    imageAlt: "Irene Adler's cabinet photograph on the 221B mantelpiece, magnifying glass before it",
    flavor:
      "He referred to her as 'the woman.' He had no other category for her. I asked once if this was admiration or defeat. He did not answer, which was an answer.",
    flavorAttrib: 'Watson, casebook, suppressed',
    echo: 'The photograph was taken at a studio in Prague, per the cartouche on its back — a city neither of them had reason to visit in the known cases. The studio name is in a language neither Holmes nor Adler spoke.',
  },
  {
    id: 'bs1-r04',
    name: 'The Case Map',
    set: 'Baker Street · BS-1',
    tier: 'Rare',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-r04/v1.webp',
    imageAlt: 'Holmes at the center of a circle of case documents spread across the 221B floor',
    flavor:
      'Contents of the floor circle, 2 Nov 1884: eleven items. Items removed by Holmes before I could catalogue them: four. The four are not described in the public account.',
    flavorAttrib: 'Watson',
    echo: "One of the four items was a railway timetable for a line that, as of November 1884, had not yet opened. Watson's subsequent correction in a later note reads only: 'I must have miscounted.'",
  },
  {
    id: 'bs1-c11',
    name: 'The Coded Message',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c11/v1.webp',
    imageAlt: 'Holmes in the 221B armchair, cipher papers radial on the floor, pen raised at the moment of decision',
    flavor: 'He circled the third symbol. Seven drafts in the grate.',
    flavorAttrib: 'Watson, casebook',
    echo: 'The third symbol Holmes circled appears in an unpublished Watson correspondence dated six years later. He never explained the recurrence.',
  },
  {
    id: 'bs1-c12',
    name: 'The Gaslight Vigil',
    set: 'Baker Street · BS-1',
    tier: 'Common',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-c12/v1.webp',
    imageAlt: 'Holmes standing at the 221B first-floor window at 3AM, greatcoat still on, London fog at the two-inch gap',
    flavor: 'It was 3AM. He had not removed his coat.',
    flavorAttrib: 'Watson, casebook',
    echo: 'The 221B accounts record a broken window latch repaired three winters running. Watson noted the cost; he did not date the repairs.',
  },
  {
    id: 'bs1-r05',
    name: 'The Moriarty Letter',
    set: 'Baker Street · BS-1',
    tier: 'Rare',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-r05/v1.webp',
    imageAlt: 'Holmes standing at the 221B desk, holding a single letter in both hands with deliberate lightness',
    flavor: 'He read it twice. The second reading was slower, which meant the first had been correct.',
    flavorAttrib: 'Watson, casebook',
    echo: "The letter was never described in Watson's published casebook. A fragment matching its handwriting appears, attributed to 'a correspondent who did not survive,' in Watson's unsorted papers.",
  },
  {
    id: 'bs1-l02',
    name: 'The Seven-Per-Cent',
    set: 'Baker Street · BS-1',
    tier: 'Legendary',
    shell: 'PRIME',
    imagePath: '/prototype-art/bs-1-221b/bs1-l02/v1.webp',
    imageAlt: 'Holmes seated in the 221B armchair, Morocco case open at the armrest with hypodermic needle, looking directly at the viewer',
    flavor: 'The case was open when I came in. I pretended not to see it. He noticed that I pretended, and was grateful.',
    flavorAttrib: 'Watson, casebook, suppressed',
    echo: "The Morocco case appears in Watson's private inventory of 221B without a quantity listed. The inventory was written in 1888 and was not revised.",
  },
];

export function getCardById(id: string): LatticeCard | undefined {
  return LATTICE_CARDS.find((c) => c.id === id);
}
